CREATE DATABASE ghid_turistic;
USE ghid_turistic;

CREATE TABLE destinatii (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    descriere TEXT,
    imagine VARCHAR(255) -- Stocăm URL-ul imaginii
);

INSERT INTO destinatii (nume, descriere, imagine) VALUES
('Palatul Parlamentului', 'Palatul Parlamentului din București, România, măsoară 270 m pe 240 m, 84 m înălțime și 92 m sub pământ. Conform World Records Academy, este a treia cea mai mare clădire administrativă pentru uz civil din lume, cea mai scumpă și cea mai grea clădire din lume.', 'images/palatul_parlamentului.jpg'),
('Castelul Bran', 'Castelul Bran, situat aproape de Brașov, este adesea asociat cu legenda lui Dracula. Deși legătura cu Vlad Țepeș este mai mult literară decât istorică, castelul atrage mii de turiști anual.', 'images/castelul_bran.jpg'),
('Delta Dunării', 'Delta Dunării este cea mai mare și mai bine conservată deltă din Europa. Sit UNESCO, adăpostește sute de specii rare de păsări și animale sălbatice, fiind un paradis pentru iubitorii de natură.', 'images/delta_dunarii.jpg'),
('Transfăgărășan', 'Transfăgărășanul, cunoscut ca DN7C, traversează Munții Făgăraș. Construit în anii ’70, oferă peisaje spectaculoase și este accesibil doar vara, din cauza condițiilor meteorologice dure.', 'images/transfagarasan.jpg'),
('Castelul Corvinilor', 'Castelul Corvinilor din Hunedoara, un impresionant castel gotic din secolul XV, a fost construit de Ioan de Hunedoara. Este faimos pentru arhitectura sa spectaculoasă și legendele sale medievale.', 'images/castelul_corvinilor.jpg'),
('Salina Turda', 'Salina Turda datează din perioada romană și a fost exploatată timp de peste 2.000 de ani. Restaurată în 2010, este acum una dintre cele mai spectaculoase atracții turistice subterane din România.', 'images/salina_turda.jpg'),
('Mocănița de pe Valea Vaserului', 'Mocănița din Maramureș este ultima locomotivă cu aburi din lume care funcționează pentru transport și turism. Traseul său străbate peisaje sălbatice deosebite.', 'images/mocanita_vaser.jpg'),
('Cazanele Dunării', 'Cazanele Dunării, situate în județul Mehedinți, sunt o zonă spectaculoasă unde fluviul Dunărea străbate Munții Carpați. Atractii includ Chipul lui Decebal și Mănăstirea Mraconia.', 'images/cazanele_dunarii.jpg'),
('Cimitirul Vesel de la Săpânța', 'Cimitirul Vesel din Săpânța este faimos pentru crucile viu colorate și epitafurile satirice, care descriu viața celor îngropați într-un mod unic și plin de umor.', 'images/cimitirul_vesel.jpg'),
('Cetatea Alba Carolina', 'Cetatea Alba Carolina, situată în Alba Iulia, este cea mai mare cetate din România, construită în stil Vauban în secolul XVIII. Este un simbol important al Unirii din 1918.', 'images/cetatea_alba_carolina.jpg');

CREATE TABLE detalii_destinatii (
    id INT AUTO_INCREMENT PRIMARY KEY,
    destinatie_id INT NOT NULL,
    descriere_lunga TEXT NOT NULL,
    galerie_foto TEXT NOT NULL,
    FOREIGN KEY (destinatie_id) REFERENCES destinatii(id) ON DELETE CASCADE
);

INSERT INTO detalii_destinatii (destinatie_id, descriere_lunga, galerie_foto) VALUES
(1, 'Palatul Parlamentului din București, România (cunoscut înainte de revoluția din 1989 sub numele de Casa Republicii sau Casa Poporului) măsoară 270 m pe 240 m, 84 m înălțime și 92 m sub pământ, realizat în spiritul arhitecturii realist-socialiste. Are 9 niveluri la suprafață și alte 9 subterane. Conform World Records Academy, Palatul Parlamentului este a treia cea mai mare clădire administrativă pentru uz civil ca suprafață din lume, cea mai scumpă clădire administrativă din lume și cea mai grea clădire din lume. Clădirea este situată în partea centrală a Bucureștiului (sector 5), pe Dealul Arsenalului, încadrat de strada Izvor la vest și nord-vest, Bulevardul Națiunile Unite spre nord, Bulevardul Libertății la est și Calea 13 Septembrie la sud.','images/parlament1.jpg,images/parlament2.jpg,images/parlament3.jpg,images/parlament4.jpg'),
(2, 'Castelul Bran, situat în inima Transilvaniei, aproape de Brașov, este adesea asociat cu legenda lui Dracula, figura iconică a lui Vlad Țepeș, domnitorul Valahiei cunoscut pentru lupta împotriva invadatorilor otomani. Deși conexiunea dintre Vlad Țepeș și castel este mai mult o creație literară decât una istorică, aceasta nu a împiedicat mii de turiști să viziteze acest misterios castel în căutarea poveștilor de vampiri.', 'images/castelul_bran1.jpg,images/castelul_bran2.jpg,images/castelul_bran3.jpg,images/castelul_bran4.jpg'),
(3, 'Delta Dunării, cea mai mare și cea mai bine conservată deltă din Europa, este un ecosistem unic situat în estul României, unde Dunărea se varsă în Marea Neagră. Este recunoscută ca sit UNESCO pentru biodiversitatea sa extraordinară, găzduind sute de specii de păsări, pești și alte animale sălbatice, multe dintre ele fiind rare sau amenințate cu dispariția. Printre cele mai cunoscute specii se numără pelicani, lebede, egrete și cormorani, care atrag pasionați de birdwatching din întreaga lume.','images/delta1.jpg,images/delta2.jpg,images/delta3.jpg,images/delta4.jpg'),
(4, 'Transfăgărășanul, oficial cunoscut ca DN7C, este un drum montan care traversează Munții Făgăraș, cei mai înalți munți din România. Construit în anii ’70 la ordinul lui Nicolae Ceaușescu, acesta a fost conceput ca o rută strategică militară și se întinde pe aproximativ 90 de kilometri, oferind unele dintre cele mai impresionante și dramatice peisaje montane din țară. Drumul este cunoscut pentru serpentinele sale înguste, tunelurile săpate în stâncă și viaductele spectaculoase, fiind deschis traficului doar în lunile de vară din cauza condițiilor meteorologice severe din restul anului.','images/trans1.jpg,images/trans2.jpg,images/trans3.jpg,images/trans4.jpg'),
(5, 'Castelul Corvinilor, situat în Hunedoara, este un impresionant castel gotic din secolul XV, construit de Ioan de Hunedoara. Renumit pentru arhitectura sa spectaculoasă, include turnuri impunătoare, Sala Cavalerilor și o fântână legendară săpată de prizonieri turci.','images/castelul_corvinilor1.jpg,images/castelul_corvinilor2.jpg,images/castelul_corvinilor3.jpg,images/castelul_corvinilor4.jpg'),
(6, 'Salina Turda datează din perioada romană, fiind exploatată pentru sare de peste 2.000 de ani. Primele atestări documentare datează din anul 1075, iar în Evul Mediu extracția sării era una dintre principalele activități economice din zonă. Începând cu secolul al XVII-lea, mina a fost extinsă, săpându-se manual galeriile care astăzi impresionează turiștii. Exploatarea sării a fost o activitate intensă până în 1932, când a fost închisă din motive economice. Timp de aproape 80 de ani, galeriile au fost folosite ocazional ca depozite sau adăposturi în perioade de război. În 2010, salina a fost restaurată și transformată într-unul dintre cele mai spectaculoase obiective turistice din România.','images/salina_turda1.jpg,images/salina_turda2.jpg,images/salina_turda3.jpg,images/salina_turda4.jpg'),
(7, 'De luni până sâmbătă, din mai și până în octombrie, de 84 de ani, locomotiva Mocănița străbate aceeași rută de 21,6 kilometri între Vișeu și Paltin pentru a transporta lemne și pentru a încânta turiștii. Ultima locomotivă cu aburi din lume pleacă la ora 9 dimineața, te poartă prin plaiuri unde natura abia a fost atinsă de mâna omului și te aduce înapoi la ora 15. Dacă vrei să te bucuri pe deplin de acest drum, îți trebuie musai o companie pe măsură, fie ea și o carte de suflet.', 'images/mocanita1.jpg,images/mocanita2.jpg,images/mocanita3.jpg,images/mocanita4.jpg'),
(8, 'Cazanele Dunării, situate lângă Dubova, județul Mehedinți, sunt una dintre cele mai spectaculoase zone naturale din România. Aici, Dunărea străbate Munții Carpați, formând un defileu impresionant cu pereți stâncoși abrupți. Atracții emblematice includ Chipul lui Decebal, Mănăstirea Macronia și Peștera Ponicova. Loc ideal pentru croaziere și drumeții.','images/cazane1.jpg,images/cazane2.jpg,images/cazane3.jpg,images/cazane4.jpg'),
(9, 'Cimitirul Vesel din Săpânța, județul Maramureș, este celebru pentru crucile viu colorate și epitafurile satirice care descriu viața celor îngropați. A fost creat de Stan Ioan Pătraș în anii 1930, artist popular care a sculptat și pictat primele cruci. Crucile sunt decorate în stil tradițional maramureșean, predominant albastru, și ilustrează, prin picturi naive, meseria sau modul în care persoana a trăit ori a murit. Pe fiecare cruce se găsesc epitafuri amuzante sau ironice, scrise în versuri, care adesea conțin umor și înțelepciune populară.', 'images/sapanta1.jpg,images/sapanta2.jpg,images/sapanta3.jpg,images/sapanta4.jpg'),
(10, 'Cetatea Alba Carolina, din Alba Iulia, județul Alba, este cea mai mare cetate din România, construită în stil Vauban în secolul XVIII. Are șapte bastioane, porți impunătoare și găzduiește Catedrala Reîntregirii. Simbol al Unirii din 1918, este o atracție turistică de top, plină de istorie.', 'images/alba1.jpg,images/alba2.jpg,images/alba3.jpg,images/alba4.jpg');
# se pot pune infinite (sau nici chiar) imagini cu virgula intre ele sau cu update
# UPDATE detalii_destinatii 
# SET galerie_foto = CONCAT(galerie_foto, ',images/palat4.jpg') 
# WHERE destinatie_id = 1;

CREATE TABLE orase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL, 
    descriere TEXT,
    imagine VARCHAR(255)
);

INSERT INTO orase (nume, descriere, imagine) VALUES
('Alba-Iulia', 'Alba Iulia este un oraș situat în centrul României, în județul Alba, cunoscut pentru importanța sa istorică și culturală. Este reședința județului și unul dintre cele mai vechi orașe din țară, având o istorie ce datează de mai bine de două milenii.', 'images/alba_iulia.jpg'),
('Arad', 'Aradul este un important centru cultural, cu teatre, muzee și evenimente. Orașul este cunoscut pentru arhitectura sa eclectic, inclusiv clădiri în stil baroc și secessionist. De asemenea, este un nod feroviar major al regiunii.', 'images/arad.jpg'),
('Bacau', 'Bacău este un important centru cultural din Moldova, cunoscut pentru Biserica Precista și Palatul de Justiție. Orașul oferă o viață culturală vibrantă, cu teatre și muzee, fiind și un punct educațional semnificativ.', 'images/bacau.jpg'),
('Baia Mare', 'Baia Mare, un oraș cu o istorie fascinantă, se dezvoltă rapid în domeniul tehnologiei și educației. Orașul este cunoscut pentru peisajele sale montane și atracțiile naturale, dar și pentru comunitățile tradiționale și atmosfera primitoare.', 'images/baia_mare.jpg'),
('Bistrița', 'Bistrița, un oraș transilvănean cu tradiție medievală, se remarcă prin arhitectura sa istorică, atracții culturale și oportunități de turism montan, având legături strânse cu istoria și tradițiile regiunii.', 'images/bistrita.jpg'),
('Botoșani', 'Botoșani, un oraș cu istorie și tradiție în Moldova, se remarcă prin arhitectura eclectică, viața culturală activă și legăturile cu natura, fiind un loc ideal pentru turism montan și explorare a patrimoniului local.', 'images/botosani.jpg'),
('Brașov', 'Brașov, situat în inima Transilvaniei, este un oraș cu peisaje montane uimitoare și o istorie îndelungată. Atracțiile sale includ Biserica Neagră, Castelul Bran și Poiana Brașov, o destinație populară pentru sporturile de iarnă.', 'images/brasov.jpg'),
('București', 'București, capitala României, este cel mai mare oraș al țării, centru economic, cultural și politic. Atestat din 1459, îmbină arhitectura veche și modernă, având repere precum Palatul Parlamentului, Ateneul Român și Arcul de Triumf.', 'images/bucuresti.jpg'),
('Cluj-Napoca', 'Cluj-Napoca, inima Transilvaniei, îmbină patrimoniul istoric cu inovația tehnologică. Cu o scenă academică de elită, startup-uri IT și efervescență culturală, orașul modelează viitorul României într-un peisaj urban sofisticat.', 'images/cluj.jpg'),
('Constanța', 'Constanța este un oraș cosmopolit, unde tradiția întâlnește modernitatea. Cu un mix vibrant de culturi, festivaluri maritime, gastronomie diversă și dezvoltare urbană accelerată, atrage turiști, investitori și pasionați de navigație.', 'images/constanta.jpg'),
('Covasna', 'Covasna este un județ montan, cunoscut pentru stațiunile balneare și peisajele sale spectaculoase. Vizitatorii pot explora tradițiile secuiești, drumețiile montane și izvoarele minerale, într-o atmosferă relaxantă și plină de istorie.', 'images/covasna.jpg'),
('Craiova', 'Craiova, un oraș plin de viață din sud-vestul României, se remarcă prin arhitectura sa impresionantă, parcurile vaste și evenimentele culturale diverse. Aici se află Universitatea din Craiova, Grădina Botanică și faimosul Parc Nicolae Romanescu.', 'images/craiova.jpg'),
('Deva', 'Deva impresionează prin Cetatea sa medievală, ce domină orașul de pe un deal vulcanic. Orașul are o bogată viață culturală, fiind aproape de Castelul Corvinilor și de stațiunea Geoagiu-Băi, renumită pentru apele sale termale.', 'images/deva.jpg'),
('Harghita', 'Harghita este un județ montan, celebru pentru Lacul Roșu, Cheile Bicazului și stațiunile Borsec și Băile Tușnad. Zona oferă peisaje superbe, tradiții secuiești autentice și sporturi de iarnă pe Pârtia Harghita Mădăraș.', 'images/harghita.jpg'),
('Iași', 'Iași, fosta capitală a Moldovei, impresionează prin universități de prestigiu, centre de cercetare, arhitectură splendidă, festivaluri culturale și un dinamism economic în creștere.', 'images/iasi.jpg'),
('Oradea', 'Oradea, cu un mix de tradiție și modernitate, se remarcă prin dezvoltarea sectorului turistic, centrele comerciale și infrastructura de transport. Orașul este cunoscut și pentru calitatea vieții și atmosfera sa prietenoasă, atrăgând tineri din întreaga țară.', 'images/oradea.jpg'),
('Piatra Neamț', 'Piatra-Neamț, „Perla Moldovei”, impresionează prin peisaje montane superbe și obiective precum Turnul lui Ștefan cel Mare, Curtea Domnească și telegondola. În apropiere, Cheile Bicazului și Lacul Izvorul Muntelui atrag iubitorii naturii și aventurii.', 'images/piatra_neamt.jpg'),
('Pitești', 'Pitești, un oraș istoric din Muntenia, se remarcă prin tradițiile sale, atracțiile culturale și dezvoltarea economică, fiind un centru important al regiunii Argeș, cu o viață urbană dinamică.', 'images/pitesti.jpg'),
('Ploiești', 'Ploiești este un oraș industrial important, cunoscut pentru tradiția sa în rafinarea petrolului. Pe lângă industrie, orașul oferă atracții culturale, muzee, teatre și parcuri, fiind un centru economic și artistic cu o istorie fascinantă.', 'images/ploiesti.jpg'),
('Sibiu', 'Sibiu impresionează prin arhitectura medievală, piețele sale vibrante și atmosfera sa culturală unică. Muzee celebre, festivaluri și obiective iconice precum Podul Minciunilor transformă orașul într-o destinație de neratat pentru iubitorii de istorie și artă.', 'images/sibiu.jpg'),
('Timișoara', 'Timișoara, numită și „Mica Vienă”, impresionează prin arhitectura sa barocă, spațiile verzi generoase și scena culturală vibrantă. Oraș inovator, a fost primul din Europa iluminat electric stradal în 1884.', 'images/timisoara.jpg');

CREATE TABLE detalii_orase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    orase_id INT NOT NULL,
    descriere_lunga TEXT NOT NULL,
    galerie_foto TEXT NOT NULL,
    FOREIGN KEY (orase_id) REFERENCES orase(id) ON DELETE CASCADE
);

INSERT INTO detalii_orase (orase_id, descriere_lunga, galerie_foto) VALUES
(1,'Alba Iulia este un oraș cu o istorie fascinantă, fiind cunoscut pentru rolul său în unirea Transilvaniei cu România în 1918. Cetatea Alba Carolina, o fortificație impresionantă în stil Vauban, este una dintre cele mai mari atracții ale orașului, fiind restaurată cu grijă și oferind o privire asupra trecutului medieval al regiunii. Orașul găzduiește și numeroase monumente istorice, biserici și muzee, printre care Muzeul Național al Unirii, care povestește despre evenimentele care au marcat unirea. Alba Iulia este, de asemenea, un centru educațional și cultural, fiind locul unde se desfășoară diverse evenimente și festivaluri pe tot parcursul anului.', 'images/alba_iulia1, images/alba_iulia2, images/alba_iulia3, images/alba_iulia4'),
(2,'Aradul este situat în extremitatea vestică a României, în Câmpia înaltă a Aradului, la 30 de km de Munții Zarand, parte a Carpaților Occidentali. Traversat de la est la vest de râul Mureș, cuprinde în perimetrul său, în zona Pădurice, un lac natural. Pe parcursul secolelor XIX și XX, Aradul s-a afirmat ca unul dintre cele mai importante centre economice din regiune. În acest sens semnificativă este evaluarea făcută în anul 1937, potrivit căreia, raportat la activitatea celor 4001 societăți comerciale, orașul a fost considerat drept cel mai puternic centru economic din Transilvania și al patrulea din România.', 'images/arad1.jpg, images/arad2.jpg,images/arad3.jpg,images/arad4.jpg'),
(3,'Bacău este un oraș situat în partea de est a României, în regiunea Moldova, fiind un important centru economic, cultural și educațional. Orașul are o istorie ce datează din perioada medievală, având multiple monumente și clădiri istorice. Printre atracțiile importante se numără Biserica Precista, un exemplu remarcabil de arhitectură moldovenească, și Palatul de Justiție, o clădire impunătoare din secolul al XIX-lea. Bacău este, de asemenea, un oraș cu o viață culturală activă, găzduind teatre, muzee și galerii de artă. De asemenea, orașul este cunoscut pentru infrastructura sa educațională, cu instituții precum Universitatea „Vasile Alecsandri”. Regiunea din jurul Bacăului oferă oportunități pentru turism montan și activități în natură, fiind în apropierea Munților Carpați.', 'images/bacau1.jpg, images/bacau2.jpg,images/bacau3.jpg,images/bacau4.jpg'),
(4,'Baia Mare este un oraș situat în nord-vestul României, în regiunea Maramureș, cunoscut pentru istoria sa minieră și peisajele montane. Orașul este renumit pentru Monumentul Minerului, un important simbol al orașului, dar și pentru Biserica Sfântul Nicolae, un monument istoric semnificativ. Baia Mare este un important centru cultural, cu teatre, muzee, galerii de artă și evenimente culturale care reflectă tradițiile și diversitatea regiunii. De asemenea, orașul se remarcă printr-o dezvoltare economică sustenabilă, cu o infrastructură modernă și un climat prietenos pentru turiști și investitori, fiind un punct de atracție al zonei.', 'images/baia_mare1.jpg,images/baia_mare2.jpg,images/baia_mare3.jpg,images/baia_mare4.jpg'),
(5,'Bistrița este un oraș situat în nord-estul României, în regiunea Transilvania, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa medievală, cu clădiri istorice bine conservate, dar și pentru atmosfera sa boemă. Bistrița este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „Vasile Goldiș”. Orașul este situat în apropierea Munților Călimani, oferind oportunități pentru turism montan și de agrement.','images/bistrita1.jpg, images/bistrita2.jpg, images/bistrita3.jpg, images/bistrita4.jpg'),
(6,'Botoșani este un oraș situat în nord-estul României, în regiunea Moldova, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa eclectică, cu influențe baroce și neogotice, dar și pentru atmosfera sa boemă. Botoșani este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „Ștefan cel Mare”. Orașul este situat în apropierea Munților Mestecăniș, oferind oportunități pentru turism montan și de agrement.', 'images/botosani1.jpg,images/botosani2.jpg, images/botosani3.jpg, images/botosani4.jpg'),
(7,'Brașov este un oraș situat în inima României, în regiunea Transilvania, la poalele Munților Carpați. Cu o istorie de peste 800 de ani, Brașov este renumit pentru peisajele montane impresionante și pentru centrul său istoric bine conservat, care include Biserica Neagră și Piața Sfatului. Orașul este un important centru turistic și cultural, atrăgând vizitatori din întreaga lume datorită atracțiilor precum Castelul Bran, cunoscut și sub numele de Castelul lui Dracula, și Poiana Brașov, o stațiune montană celebră pentru sporturile de iarnă. De asemenea, Brașov este un important centru educațional, găzduind universități și școli de renume. Atmosfera sa vibrantă și combinația între istorie și modernitate fac din Brașov un loc deosebit de vizitat.', 'images/brasov1.jpg, images/brasov2.jpg, images/brasov3.jpg, images/brasov4.jpg'),
(8,'București este capitala și cel mai mare oraș din România, având o istorie de peste 500 de ani. Orașul se distinge printr-o combinație interesantă de arhitectură istorică și modernă, cu clădiri de epocă, precum Palatul Parlamentului, și structuri contemporane. București este un important centru cultural, cu teatre, muzee și galerii de artă, iar viața sa urbană este animată de restaurante, cafenele și evenimente diverse. Orașul este, de asemenea, un hub economic major, găzduind multe instituții financiare și companii internaționale. Deși provocările urbane sunt prezente, Bucureștiul rămâne un loc dinamic și plin de oportunități.', 'images/bucuresti1.jpg, images/bucuresti2.jpg, images/bucuresti3.jpg, images/bucuresti4.jpg' ),
(9,'Cluj-Napoca este un oraș vibrant situat în centrul Transilvaniei, România, cunoscut pentru rolul său important în educație, cultură și tehnologie. Aflat pe malurile Someșului, Cluj-Napoca este un centru universitar major, găzduind Universitatea Babeș-Bolyai, una dintre cele mai vechi și prestigioase din țară. Orașul se remarcă printr-un amestec de arhitectură istorică, cum ar fi Biserica Sf. Mihail, și dezvoltări moderne, cu o viață culturală activă, evenimente și festivaluri internaționale. Cluj-Napoca este, de asemenea, un important centru tehnologic, fiind cunoscut ca un hub IT în creștere. Atmosfera sa cosmopolitană atrage turiști și investitori din întreaga lume.', 'images/cluj1.jpg, images/cluj2.jpg, images/cluj3.jpg, images/cluj4.jpg'),
(10,'Constanța este un oraș situat pe coasta Mării Negre, fiind cel mai important port al României și unul dintre cele mai vechi orașe din țară, cu o istorie ce datează de peste 2.500 de ani. Cunoscut pentru atracțiile sale turistice, Constanța oferă plaje extinse, un climat blând și o combinație de influențe culturale și istorice, inclusiv vestigii ale civilizațiilor grecești și romane. Printre obiectivele notabile se numără Cazinoul, Muzeul de Istorie Națională și Arheologie, dar și portul, care joacă un rol economic esențial. Orașul este, de asemenea, un important centru comercial și cultural al regiunii.', 'images/constanta1.jpg, images/constanta2.jpg, images/constanta3.jpg, images/constanta4.jpg'),
(11,'Covasna este un județ situat în centrul României, renumit pentru peisajele sale montane și stațiunile balneare. Orașul Covasna, reședința județului, este faimos pentru izvoarele sale minerale și pentru atmosfera relaxantă. Județul oferă multiple oportunități de turism, atât de agrement, cât și de sănătate, datorită stațiunilor precum Bucin și Întorsura Buzăului, care atrag turiști din întreaga țară. Regiunea este cunoscută pentru tradițiile sale secuiești, care se reflectă în festivaluri, meșteșuguri și gastronomie. Munții Întorsurii și Masivul Ciucaș sunt ideale pentru drumeții și sporturi montane. Pe lângă frumusețea naturală, Covasna are și un patrimoniu cultural deosebit, cu biserici vechi, monumente istorice și o populație primitoare, ceea ce face din județ o destinație deosebită pentru vizitatori.', 'images/covasna1.jpg, images/covasna2.jpg, images/covasna3.jpg, images/covasna4.jpg'),
(12,'Craiova, situată în sud-vestul României, este un oraș cu o istorie bogată și un centru economic, cultural și educațional important. Fiind reședința județului Dolj, orașul impresionează prin arhitectura sa variată, ce îmbină stilurile neoclasic, modern și brâncovenesc. Unul dintre cele mai mari parcuri naturale din țară, Parcul Nicolae Romanescu, oferă un peisaj spectaculos, cu lacuri, poduri și grădini pitorești. Teatrul Național „Marin Sorescu”, Muzeul de Artă și Catedrala Mitropolitană Sfântul Dumitru sunt câteva dintre obiectivele culturale deosebite. Craiova este și un important centru universitar, găzduind Universitatea din Craiova. Economia locală este susținută de industria auto, cu fabrica Ford, dar și de comerț și servicii moderne. Orașul are o viață activă, cu festivaluri și evenimente artistice anuale.', 'images/craiova1.jpg'),
(13,'Deva este un oraș din vestul României, situat în județul Hunedoara, recunoscut pentru importanța sa istorică și culturală. Cel mai emblematic obiectiv turistic este Cetatea Devei, o fortificație medievală impresionantă, amplasată pe un deal vulcanic ce oferă o panoramă spectaculoasă asupra orașului. Deva este un important centru administrativ și economic al regiunii, având o dezvoltare continuă în domeniul comerțului și turismului. În apropiere se află Castelul Corvinilor din Hunedoara, unul dintre cele mai frumoase castele gotice din Europa. De asemenea, orașul este cunoscut pentru Școala Gimnazială de Arte și pentru diverse evenimente culturale organizate anual. Nu departe de Deva se află stațiunea balneoclimaterică Geoagiu-Băi, recunoscută pentru apele sale termale benefice.', 'images/deva1.jpg, images/deva2.jpg, images/deva3.jpg, images/deva4.jpg'),
(14,'Harghita este un județ situat în centrul României, în inima Transilvaniei, fiind renumit pentru peisajele sale montane spectaculoase, cultura secuiască și tradițiile bine păstrate. Zona este un important centru al turismului montan și balnear, cu atracții precum Lacul Roșu, Cheile Bicazului și stațiunile Borsec și Băile Tușnad, faimoase pentru apele minerale terapeutice. Harghita este cunoscută și pentru Pârtia Harghita Mădăraș, populară în rândul iubitorilor sporturilor de iarnă. Un alt punct de atracție este izvorul natural de la Băile Harghita, cu ape bogate în minerale. Cultura locală este influențată puternic de comunitatea maghiară, iar gastronomia specifică, cu preparate precum gulașul secuiesc și cozonacul kurtoskalacs, atrage numeroși turiști.', 'images/harghita1.jpg, images/harghit2a.jpg, images/harghita3.jpg, images/harghita4.jpg'),
(15,'Iași este un oraș istoric situat în nord-estul României, fiind considerat capitala culturală a regiunii Moldova. Cu o istorie de peste 600 de ani, Iași a fost un important centru al educației și al religiei, găzduind cele mai vechi instituții de învățământ superior din țară, cum ar fi Universitatea „Alexandru Ioan Cuza”. Orașul este renumit pentru monumentele sale istorice, inclusiv Palatul Culturii și Biserica Trei Ierarhi, dar și pentru viața culturală activă. Iași este, de asemenea, un important centru economic, cu o dezvoltare semnificativă în domenii precum IT-ul, sănătatea și industria farmaceutică.', 'images/iasi1.jpg, images/iasi2.jpg, images/iasi3.jpg, images/iasi4.jpg'),
(16,'Oradea este un oraș fascinant, cunoscut pentru arhitectura sa unică, cu influențe baroce și secessioniste. Palatul Vulturul Negru și Biserica cu Lună sunt doar câteva dintre monumentele sale remarcabile. Oradea este, de asemenea, un important centru termal, având băi termale care atrag turiști din întreaga lume. Orașul se află aproape de granița cu Ungaria, ceea ce îi conferă un caracter cosmopolit, iar apropierea de stațiunile de ski și de lacurile de agrement face din Oradea o destinație turistică versatilă. Oradea găzduiește și Universitatea din Oradea, un important centru educațional al regiunii.', 'images/oradea1.jpg, images/oradea2.jpg, images/oradea3.jpg, images/oradea4.jpg'),
(17,'Piatra-Neamț, situat în nord-estul României, este unul dintre cele mai pitorești orașe din Moldova, fiind înconjurat de Munții Carpați și traversat de râul Bistrița. Orașul este supranumit „Perla Moldovei” datorită peisajelor sale montane impresionante și a aerului curat. Printre principalele atracții turistice se numără Cetatea Neamțului, Curtea Domnească și Turnul lui Ștefan cel Mare, simboluri istorice importante. De asemenea, turiștii pot vizita Mănăstirea Bistrița, Mănăstirea Văratec sau pot explora Cheile Bicazului și Lacul Izvorul Muntelui, aflate în apropiere. Piatra-Neamț oferă și oportunități de agrement, având o telegondolă modernă ce oferă o panoramă spectaculoasă asupra orașului. Stațiunea Durău, situată în apropiere, este o destinație populară pentru iubitorii sporturilor de iarnă.',',images/piatra_neamt1.jpg, images/piatra_neamt2.jpg, images/piatra_neamt3.jpg, images/piatra_neamt4.jpg'),
(18,'Pitești, un oraș cu o istorie ce se întinde pe mai multe secole, este un centru important al regiunii Muntenia. Orașul este renumit pentru industrie, în special pentru fabrica de automobile Dacia, și pentru tradițiile sale culturale, care se reflectă în festivaluri și evenimente locale. Pitești găzduiește instituții educaționale și este un nod de transport esențial în sudul României. De asemenea, orașul se mândrește cu parcuri, zone verzi și un climat plăcut, atrăgând turiști și locuitori din întreaga țară.', 'images/pitesti1.jpg, images/pitesti2.jpg, images/pitesti3.jpg, images/pitesti4.jpg'),
(19,'Ploiești este unul dintre cele mai importante orașe din sudul României, fiind un centru economic și cultural semnificativ. Cunoscut drept „capitala aurului negru”, orașul a avut un rol crucial în dezvoltarea industriei petroliere, găzduind primele rafinării moderne din lume. Astăzi, Ploiești rămâne un important nod industrial și comercial. Pe lângă latura sa economică, orașul oferă numeroase atracții culturale, precum Muzeul Ceasului „Nicolae Simache”, Muzeul de Artă și Teatrul „Toma Caragiu”. Orașul este recunoscut și pentru numeroasele sale parcuri, oferind locuitorilor spații verzi pentru relaxare. De asemenea, Ploiești este gazda unor evenimente și festivaluri care promovează cultura locală. Situat aproape de București, orașul este bine conectat la rețeaua de transport națională, fiind un punct de acces important pentru turiști.', 'images/ploiesti1.jpg, images/ploiesti2.jpg, images/ploiesti3.jpg, images/ploiesti4.jpg '),
(20,'Sibiu este unul dintre cele mai frumoase orașe din România, situat în inima Transilvaniei. Cunoscut pentru arhitectura sa medievală impresionantă, orașul a fost Capitală Culturală Europeană în 2007, atrăgând anual mii de turiști. Centrul istoric este dominat de Piața Mare, Piața Mică și Podul Minciunilor, simboluri ale orașului. Turnul Sfatului oferă o priveliște spectaculoasă asupra întregii zone. Sibiu este și un important centru cultural, cu muzee precum Muzeul Național Brukenthal și Muzeul ASTRA, unul dintre cele mai mari muzee în aer liber din Europa. De asemenea, orașul este renumit pentru festivalurile sale, precum Festivalul Internațional de Teatru. Cu un aer boem și influențe germane puternice, Sibiu este o destinație ideală pentru iubitorii de cultură și istorie.', 'images/sibiu1.jpg, images/sibiu2.jpg, images/sibiu3.jpg, images/sibiu4.jpg'),
(21,'Sighetu Marmației este un oraș situat în nord-vestul României, în regiunea Maramureș, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Memorialul Victimelor Comunismului și al Rezistenței, un important loc de comemorare, dar și pentru Biserica „Sf. Nicolae”, un important centru religios. Sighetu Marmației este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat în apropierea Munților Maramureș, oferind oportunități pentru turism montan și de agrement.', 'images/sighetu_marmatiei1.jpg, images/sighetu_marmatiei2.jpg, images/sighetu_marmatiei3.jpg, images/sighetu_marmatiei4.jpg'),
(22,'Suceava este un oraș situat în nordul României, în regiunea Bucovina, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Cetatea de Scaun a Sucevei, un important monument istoric, dar și pentru Mănăstirea Sfântul Ioan cel Nou, un important centru religios. Suceava este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat în apropierea Munților Carpați, oferind oportunități pentru turism montan și de agrement.', 'images/suceava1.jpg, images/suceava2.jpg, images/suceava3.jpg, images/suceava4.jpg'),
(23,'Târgu Mureș este un oraș situat în centrul României, însssaasddfgg  regiunea Transilvania, cunoscut pentru arhitectura sa eclectică și atmosfera sa cosmopolită. Orașul este renumit pentru Palatul Culturii, un important monument istoric, dar și pentru Piața Trandafirilor, un loc popular de întâlnire. Târgu Mureș este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea de Medicină și Farmacie. Orașul este situat în apropierea Munților Călimani, oferind oportunități pentru turism montan și de agrement.', 'images/targu_mures1.jpg, images/targu_mure2s.jpg, images/targu_mures3.jpg, images/targu_mures4.jpg'),
(24,'Târgu Jiu este un oraș cu o istorie fascinantă și un important centru cultural în Oltenia. Pe lângă renumele internațional adus de sculpturile lui Constantin Brâncuși, orașul oferă vizitatorilor și o mulțime de alte atracții. Parcul Central, cu lacurile sale și zona de agrement, reprezintă un loc perfect pentru relaxare. În apropiere se află și Muzeul Județean Gorj, care adăpostește o colecție vastă de obiecte istorice și culturale din zonă. Orașul este, de asemenea, un punct de plecare pentru explorarea Munților Parâng, un loc deosebit pentru iubitorii de drumeție și sporturi montane. Târgu Jiu este un centru economic în dezvoltare, cu un sector industrial diversificat, iar viața culturală este animată de evenimentele anuale care includ festivaluri de artizanat, muzică și teatru.', 'images/tg_jiu1.jpg, images/tg_jiu2.jpg, images/tg_jiu3.jpg, images/tg_jiu4.jpg'),
(25,'Timișoara este municipiul de reședință al județului Timiș, Banat, România. Se află în vestul României, aproape de frontierele cu Ungaria și Serbia, pe malul râului Bega.Numele localității provine de la cel al râului Timiș, combinat cu substantivul maghiar vár, „cetate”, adică Cetatea Timișului. Situat pe râul Bega, Timișoara este cel mai mare și important oraș al regiunii istorice Banat. Din 1848 și până în 1860 a fost capitala Voivodinei Sârbești și Banatului Timișan. După Primul Război Mondial Timișoara a intrat în componența României. În anul 1989, orașul a fost focarul Revoluției Române, care a îndepărtat de la guvernare regimul comunist.', 'images/timisoara1.jpg, images/timisoara2.jpg, images/timisoara3.jpg, images/timisoara4.jpg');


CREATE TABLE locuri_vizitat (
    id INT AUTO_INCREMENT PRIMARY KEY,
    orase_id INT NOT NULL,
    nume VARCHAR(150) NOT NULL,
    descriere TEXT NOT NULL,
    imagine VARCHAR(255),
    FOREIGN KEY (orase_id) REFERENCES orase(id) ON DELETE CASCADE
);

CREATE TABLE orased (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL, 
    descriere TEXT,
    imagine VARCHAR(255)
);

INSERT INTO orased (nume, descriere, imagine) VALUES
('Braila', 'Brăila este un municipiu din sud-estul României, situat pe malul stâng al Dunării. Este unul dintre cele mai vechi orașe din țară, menționat documentar încă din 1368. Orașul are un important trecut comercial și portuar, fiind un nod economic strategic în perioada modernă.', 'images/braila.jpg'),
('Calarasi', 'Călărași este un oraș situat în sud-estul României, la granița cu Bulgaria, pe malul Dunării. Orașul este renumit pentru frumusețea sa naturală, cu peisaje pitorești și zone verzi generoase, dar și pentru atmosfera sa liniștită și prietenoasă.', 'images/calarasi.jpg'),
('Drobeta-Turnu Severin', 'Drobeta-Turnu Severin este un oraș situat în sud-vestul României, în regiunea Oltenia, la confluența râurilor Dunărea și Jiu. Orașul este renumit pentru Monumentul Tabula Traiana, un important simbol al istoriei romane, dar și pentru Parcul Natural Porțile de Fier, o rezervație naturală protejată.', 'images/drobeta_turnu_severin.jpg'),
('Galati', 'Galați este un important municipiu din estul României, situat pe malul Dunării. Este un centru industrial și portuar major, având unul dintre cele mai mari șantiere navale din țară și un important combinat siderurgic.','images/galati.jpg'),
('Giurgiu', 'Giurgiu este un oraș situat în sudul României, la granița cu Bulgaria, pe malul Dunării. Orașul este renumit pentru Podul Prieteniei, un important simbol al relațiilor româno-bulgare, dar și pentru Cetatea Giurgiu, un monument istoric semnificativ.', 'images/giurgiu.jpg'),
('Orsova', 'Orșova este un oraș situat în sud-vestul României, pe malul Dunării, în județul Mehedinți. Este cunoscut pentru peisajele spectaculoase ale Clisurii Dunării și pentru apropierea de Cazanele Dunării, una dintre cele mai frumoase zone naturale din țară.','images/orsova.jpg'),
('Tulcea', 'Tulcea este un oraș situat în estul României, la confluența râurilor Dunărea și Sfântu Gheorghe, fiind un important centru cultural și economic al regiunii Dobrogea. Orașul este renumit pentru Delta Dunării, unul dintre cele mai mari și mai frumoase ecosisteme din Europa, dar și pentru Monumentul Independenței.', 'images/tulcea.jpg');

CREATE TABLE detalii_orased (
    id INT AUTO_INCREMENT PRIMARY KEY,
    orase_id INT NOT NULL,
    descriere_lunga TEXT NOT NULL,
    galerie_foto TEXT NOT NULL,
    FOREIGN KEY (orase_id) REFERENCES orased(id) ON DELETE CASCADE
);

INSERT INTO detalii_orased (orase_id, descriere_lunga, galerie_foto) VALUES
(1,'Cu o istorie bogată, ce datează din Evul Mediu, orașul a fost un important centru comercial și portuar, având un rol strategic datorită poziției sale pe Dunăre. Brăila este un oraș cu o istorie fascinantă, o economie în dezvoltare și un patrimoniu cultural remarcabil. Deși nu mai are aceeași importanță economică de altădată, continuă să fie un centru regional important, atrăgând turiști prin arhitectura sa deosebită, evenimentele culturale și peisajele pitorești de pe malul Dunării.', 'images/braila1.jpg, images/braila2.jpg, images/braila3.jpg, images/braila4.jpg'),
(2,'Călărași este un oraș cu o istorie îndelungată, ce datează din perioada medievală, fiind un important centru comercial și portuar. Situat pe malul Dunării, orașul oferă o combinație interesantă de istorie, cultură și natură. Călărași este renumit pentru frumusețea sa naturală, cu peisaje pitorești, dar și pentru atmosfera sa liniștită și prietenoasă. Orașul este un loc ideal pentru relaxare și explorare, oferind oportunități pentru turism, sporturi nautice și agrement.', 'images/calarasi1.jpg, images/calarasi2.jpg, images/calarasi3.jpg, images/calarasi4.jpg'),
(3,'Drobeta-Turnu Severin este un oraș cu o istorie bogată, ce datează din perioada romană, fiind un important centru strategic și comercial. Situat la confluența râurilor Dunărea și Jiu, orașul oferă o combinație interesantă de istorie, cultură și natură. Drobeta-Turnu Severin este renumit pentru Monumentul Tabula Traiana, un important simbol al istoriei romane, dar și pentru Parcul Natural Porțile de Fier, o rezervație naturală protejată. Orașul este un loc ideal pentru explorare, relaxare și turism, oferind oportunități pentru drumeții, sporturi nautice și agrement.', 'images/drobeta1.jpg, images/drobeta2.jpg, images/drobeta3.jpg, images/drobeta4.jpg'),
(4,'Galați este un oraș cu o istorie îndelungată, ce datează din perioada medievală, fiind un important centru comercial și portuar. Situat pe malul Dunării, orașul oferă o combinație interesantă de istorie, cultură și natură. Galați este renumit pentru frumusețea sa naturală, cu peisaje pitorești, dar și pentru atmosfera sa liniștită și prietenoasă. Orașul este un loc ideal pentru relaxare și explorare, oferind oportunități pentru turism, sporturi nautice și agrement.', 'images/galati1.jpg, images/galati2.jpg, images/galati3.jpg, images/galati4.jpg'),
(5,'Giurgiu este un oraș cu o istorie îndelungată, ce datează din perioada medievală, fiind un important centru comercial și portuar. Situat pe malul Dunării, orașul oferă o combinație interesantă de istorie, cultură și natură. Giurgiu este renumit pentru frumusețea sa naturală, cu peisaje pitorești, dar și pentru atmosfera sa liniștită și prietenoasă. Orașul este un loc ideal pentru relaxare și explorare, oferind oportunități pentru turism, sporturi nautice și agrement.', 'images/giurgiu1.jpg, images/giurgiu2.jpg, images/giurgiu3.jpg, images/giurgiu4.jpg'),
(6,'Orșova este un oraș cu o istorie bogată, ce datează din perioada romană, fiind un important centru strategic și comercial. Situat la confluența râurilor Dunărea și Cerna, orașul oferă o combinație interesantă de istorie, cultură și natură. Orșova este renumit pentru peisajele spectaculoase ale Clisurii Dunării și pentru apropierea de Cazanele Dunării, una dintre cele mai frumoase zone naturale din țară. Orașul este un loc ideal pentru explorare, relaxare și turism, oferind o gamă variată de activități.', 'images/orsova1.jpg, images/orsova2.jpg, images/orsova3.jpg, images/orsova4.jpg'),
(7,'Tulcea este un oraș cu o istorie îndelungată, ce datează din perioada romană, fiind un important centru comercial și portuar. Situat la confluența râurilor Dunărea și Sfântu Gheorghe, orașul oferă o combinație interesantă de istorie, cultură și natură. Tulcea este renumit pentru Delta Dunării, unul dintre cele mai mari și mai frumoase ecosisteme din Europa, dar și pentru Monumentul Independenței, un important simbol al istoriei românești. Orașul este un punct de plecare ideal pentru explorarea Deltei Dunării.', 'images/tulcea1.jpg, images/tulcea2.jpg, images/tulcea3.jpg, images/tulcea4.jpg');

CREATE TABLE statb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL, 
    descriere TEXT,
    imagine VARCHAR(255)
);

INSERT INTO statb (nume, descriere, imagine) VALUES
('Amara','Băile Amara, situat în județul Ialomița, este o stațiune balneoclimaterică renumită pentru lacul sărat Amara și nămolul sapropelic, utilizat în tratamente reumatologice și dermatologice. Orașul oferă relaxare, terapii naturale și peisaje liniștitoare, atrăgând turiști pentru sănătate și recreere.', 'images/amara.jpg'),
('Baile Felix','Băile Felix, situate lângă Oradea, sunt cea mai mare stațiune balneară din România, renumită pentru apele termale cu proprietăți terapeutice. Oferă piscine, centre spa și tratamente pentru afecțiuni reumatologice. Stațiunea atrage turiști pentru relaxare, wellness și peisajele sale pitorești, fiind deschisă tot timpul anului.', 'images/felix.jpg'),
('Baile Govora','Băile Govora, situate în județul Vâlcea, sunt renumite pentru apele minerale cu efecte terapeutice asupra afecțiunilor respiratorii și reumatismale. Stațiunea oferă aer curat, peisaje liniștite și centre de tratament, fiind o destinație ideală pentru relaxare și recuperare medicală.', 'images/govora.jpg'),
('Baile Herculne','Băile Herculane, situate în Valea Cernei, sunt cea mai veche stațiune balneară din România, cu origini romane. Renumite pentru apele termale cu proprietăți curative, atrag turiști pentru tratamente reumatologice, peisaje spectaculoase și istorie. Oferă relaxare, drumeții și explorarea vestigiilor antice.', 'images/herculane.jpg'),
('Baile Homorod','Băile Homorod, situate în județul Harghita, sunt o stațiune balneoclimaterică renumită pentru izvoarele minerale cu efecte benefice asupra sistemului digestiv și circulator. Oferă aer curat, peisaje pitorești și oportunități de relaxare, fiind o destinație ideală pentru odihnă și tratamente naturale.','images/homorod.jpg'),
('Baile Olanesti','Băile Olănești, situate în județul Vâlcea, sunt renumite pentru izvoarele minerale cu proprietăți curative, folosite în tratarea afecțiunilor renale, digestive și reumatologice. Stațiunea oferă aer curat, peisaje montane și centre de tratament, fiind o destinație ideală pentru sănătate și relaxare.', 'images/olanesti.jpg'),
('Baile Tusnad','Băile Tușnad, situate în Carpații Orientali, sunt cea mai mică stațiune balneară din România, renumită pentru apele minerale și mofetele cu efecte benefice asupra sistemului cardiovascular. Oferă aer curat, peisaje montane și activități recreative precum drumeții și băi termale, fiind o destinație ideală pentru relaxare și tratament.', 'images/tusnad.jpg'),
('Balvanyos','Balvanyos, situată în județul Covasna, este o stațiune balneoclimaterică renumită pentru mofetele sale naturale și izvoarele minerale cu efecte benefice asupra circulației sanguine. Înconjurată de peisaje montane spectaculoase, oferă acces la Lacul Sfânta Ana și Tinovul Mohoș, fiind o destinație ideală pentru relaxare și tratamente naturale.','images/balvanyos.jpg'),
('Borsec','Borsec, situat în Carpații Orientali, este o stațiune balneară renumită pentru izvoarele sale de apă minerală cu efecte terapeutice. Oferă aer curat, peisaje montane și activități recreative precum drumeții, schi și relaxare în natură. Apa minerală Borsec este apreciată atât în România, cât și internațional.', 'images/borsec.jpg'),
('Calacea','Băile Călacea, situate în județul Timiș, sunt renumite pentru apele termale cu proprietăți terapeutice, benefice pentru afecțiuni reumatologice și neurologice. Stațiunea oferă băi termale, spații de relaxare și un parc natural, fiind o destinație ideală pentru tratament și recreere.', 'images/calacea.jpg'),
('Calimanesti-Caciulata','Călimănești-Căciulata, situată pe Valea Oltului, este una dintre cele mai cunoscute stațiuni balneare din România, renumită pentru apele termale și peisajele montane spectaculoase. Oferă tratamente balneare, relaxare și atracții precum Mănăstirea Cozia și Parcul Național Cozia, fiind o destinație ideală pentru sănătate și turism.', 'images/calimanesti.jpg'),
('Lacu Rosu','Lacu Roșu, situat în Carpații Orientali, este un lac de baraj natural unic, format prin prăbușirea unui versant. Este înconjurat de peisaje spectaculoase și păduri de conifere, oferind activități precum drumeții, plimbări cu barca și explorarea Cheilor Bicazului. Destinație ideală pentru iubitorii de natură și aventură.', 'images/rosu.jpg'),
('Lacu Sarat','Lacu Sărat, situat lângă Brăila, este o stațiune balneară renumită pentru apa sărată și nămolul terapeutic, benefice în tratarea afecțiunilor reumatologice și dermatologice. Oferă baze de tratament, plajă și zone de relaxare, fiind o destinație ideală pentru sănătate și recreere.', 'images/sarat.jpg'),
('Ocna Sibiului','Ocna Sibiului, situată lângă Sibiu, este o stațiune balneară renumită pentru lacurile sărate formate în foste mine de sare, cu proprietăți terapeutice benefice pentru afecțiuni reumatologice și dermatologice. Oferă băi naturale, peisaje pitorești și relaxare, fiind supranumită „Litoralul Ardealului”.', 'images/ocna.jpg'),
('Ocna Sugatag','Ocna Șugatag, situată în Maramureș, este o stațiune balneară renumită pentru apele sărate provenite din foste mine de sare, benefice în tratarea afecțiunilor reumatologice și neurologice. Oferă băi termale, peisaje pitorești și acces la tradițiile autentice maramureșene, fiind o destinație ideală pentru relaxare și tratament.','images/sugatag.jpg'),
('Praid','Praid, situat în județul Harghita, este renumit pentru Salina Praid, una dintre cele mai mari din Europa, cu beneficii terapeutice pentru afecțiuni respiratorii. Stațiunea oferă și băi sărate, trasee de drumeție și peisaje pitorești, fiind o destinație ideală pentru relaxare, tratament și explorarea tradițiilor secuiești.','images/praid.jpg'),
('Slanic Moldova','Slănic Moldova, situată în Carpații Orientali, este o stațiune balneară renumită pentru izvoarele minerale cu proprietăți terapeutice. Oferă tratamente pentru diverse afecțiuni, aer curat, peisaje montane și activități recreative precum drumeții și sporturi de iarnă, fiind o destinație ideală pentru sănătate și relaxare.','images/slanic.jpg'),
('Sovata','Sovata, situată în inima Transilvaniei, este o stațiune balneară renumită pentru Lacul Ursu, un lac helioterm cu proprietăți terapeutice unice. Apele sărate și nămolul sunt benefice pentru afecțiuni reumatologice și ginecologice. Stațiunea oferă peisaje pitorești, trasee de drumeție și oportunități de relaxare pe tot parcursul anului.', 'images/sovata.jpg');

CREATE TABLE detalii_statb (
    id INT AUTO_INCREMENT PRIMARY KEY,
    orase_id INT NOT NULL,
    descriere_lunga TEXT NOT NULL,
    galerie_foto TEXT NOT NULL,
    FOREIGN KEY (orase_id) REFERENCES statb(id) ON DELETE CASCADE
);

INSERT INTO detalii_statb (orase_id, descriere_lunga, galerie_foto) VALUES
(1,'Amara, situată în județul Ialomița, este o destinație balneară cunoscută pentru efectele benefice ale lacului sărat și ale nămolului sapropelic. Stațiunea atrage vizitatori datorită proprietăților curative ale apei, utilizate în terapii pentru afecțiuni ale pielii și ale sistemului locomotor. Pe lângă tratamentele balneare, Amara oferă un cadru relaxant, cu aer curat și peisaje liniștite, ideale pentru odihnă și refacere. De asemenea, orașul găzduiește diverse evenimente culturale și activități de agrement, transformându-l într-o alegere potrivită atât pentru cei care caută relaxare, cât și pentru cei interesați de turismul de sănătate.','images/amara1.jpg, images/amara2.jpg, images/amara3.jpg, images/amara4.jpg'),
(2,'Băile Felix, aflate în apropierea orașului Oradea, sunt o stațiune balneară apreciată pentru izvoarele termale cu efecte curative. Apele bogate în minerale sunt utilizate în tratarea afecțiunilor reumatice, neurologice și în programe de recuperare. Stațiunea dispune de baze de tratament moderne, piscine termale și centre de wellness, oferind o experiență de relaxare pe tot parcursul anului. Climatul blând și peisajele verzi completează atmosfera de refacere. Turiștii se pot bucura atât de terapii naturale, cât și de activități recreative, făcând din Băile Felix o destinație ideală pentru sănătate și relaxare.','images/felix1.jpg, images/felix2.jpg, images/felix3.jpg, images/felix4.jpg'),
(3,'Băile Govora, aflate în județul Vâlcea, sunt o stațiune balneară apreciată pentru apele minerale bogate în iod, brom și sulf, recunoscute pentru beneficiile lor în tratarea afecțiunilor respiratorii și locomotorii. Climatul tonic, aerul ozonat și peisajele naturale oferă un cadru ideal pentru refacere și relaxare. Stațiunea dispune de baze moderne de tratament, unde se aplică proceduri balneare eficiente. Pe lângă terapii, vizitatorii se pot bucura de plimbări prin parcuri amenajate și de liniștea specifică zonei, făcând din Băile Govora o destinație ideală pentru sănătate și recreere.','images/govora1.jpg, images/govora2.jpg, images/govora3.jpg, images/govora4.jpg'),
(4,'Băile Herculane, situate în pitoreasca Vale a Cernei, sunt una dintre cele mai vechi stațiuni balneare din Europa, având origini care datează din perioada romană. Cunoscută pentru apele sale termale sulfuroase, cu efecte benefice asupra sistemului locomotor și circulator, stațiunea atrage turiști în căutare de tratamente naturale și relaxare. Pe lângă terapiile balneare, vizitatorii se pot bucura de trasee montane spectaculoase, aer curat și vestigii istorice, cum ar fi băile romane și statuia lui Hercules. Băile Herculane rămân o destinație unică, îmbinând sănătatea, natura și istoria într-un cadru impresionant.','images/herculane1.jpg, images/herculane2.jpg, images/herculane3.jpg, images/herculane4.jpg'),
(5,'Băile Homorod, situate în județul Harghita, sunt o stațiune balneoclimaterică apreciată pentru izvoarele minerale bogate în minerale, utilizate în tratarea afecțiunilor digestive și circulatorii. Zona se remarcă prin aerul curat, climatul liniștit și peisajele montane care oferă un cadru perfect pentru relaxare și refacere. Stațiunea dispune de facilități pentru tratamente balneare și recreere, atrăgând turiști în căutare de terapii naturale și odihnă activă. Băile Homorod sunt o alegere ideală pentru cei care doresc să se bucure de beneficiile naturii într-un mediu relaxant și reconfortant.','images/homorod1.jpg, images/homorod2.jpg, images/homorod3.jpg, images/homorod4.jpg'),
(6,'Băile Olănești, situate în județul Vâlcea, sunt o stațiune balneară apreciată pentru numeroasele sale izvoare minerale cu efecte terapeutice. Apele sunt recunoscute pentru beneficiile lor în tratarea afecțiunilor renale, digestive, reumatologice și dermatologice. Stațiunea oferă un cadru natural deosebit, cu aer curat și peisaje montane, ideale pentru relaxare și refacere. În plus, dispune de centre moderne de tratament și wellness, atrăgând turiști atât pentru terapii balneare, cât și pentru recreere. Băile Olănești rămân o destinație populară pentru cei care caută sănătate, liniște și natură.','images/olanesti1.jpg, images/olanesti2.jpg, images/olanesti3.jpg, images/olanesti4.jpg'),
(7,'Băile Tușnad, situate în inima Carpaților Orientali, sunt una dintre cele mai pitorești stațiuni balneare din România, apreciate pentru apele minerale și mofetele cu efecte terapeutice asupra sistemului cardiovascular și nervos. Climatul montan, aerul ozonat și peisajele spectaculoase creează un cadru perfect pentru relaxare și refacere. Stațiunea oferă baze de tratament moderne, băi termale și numeroase oportunități de recreere, precum drumeții și plimbări în natură. Datorită atmosferei sale liniștite și beneficiilor terapeutice, Băile Tușnad sunt o destinație ideală pentru cei care caută sănătate și odihnă.','images/tusnad1.jpg, images/tusnad2.jpg, images/tusnad3.jpg, images/tusnad4.jpg'),
(8,'Balvanyos, aflată în județul Covasna, este o stațiune balneoclimaterică apreciată pentru mofetele naturale și izvoarele minerale cu proprietăți terapeutice asupra circulației sanguine și sistemului respirator. Amplasată într-un cadru montan deosebit, stațiunea oferă aer curat, trasee turistice și oportunități de relaxare în mijlocul naturii. Datorită proximității față de Lacul Sfânta Ana și Tinovul Mohoș, Balvanyos atrage atât turiști în căutare de tratamente naturale, cât și iubitori de aventură și peisaje spectaculoase. Combinând beneficiile balneare cu frumusețea peisajului, stațiunea este o alegere ideală pentru sănătate și recreere.','images/balvanyos1.jpg, images/balvanyos2.jpg, images/balvanyos3.jpg, images/balvanyos4.jpg'),
(9,'Borsec, situat în inima Carpaților Orientali, este una dintre cele mai cunoscute stațiuni balneare din România, celebră pentru izvoarele sale de apă minerală cu proprietăți terapeutice. Apele de aici sunt apreciate pentru beneficiile asupra sistemului digestiv și renal, fiind recunoscute la nivel internațional. Stațiunea oferă un climat tonic, aer curat și peisaje montane spectaculoase, ideale pentru relaxare și refacere. În plus, turiștii pot practica diverse activități recreative, precum drumeții, schi și explorarea traseelor naturale. Borsec rămâne o destinație de top pentru sănătate, natură și aventură.','images/borsec1.jpg, images/borsec2.jpg, images/borsec3.jpg, images/borsec4.jpg'),
(10,'Băile Călacea, aflate în județul Timiș, sunt o stațiune balneară cunoscută pentru apele termale cu efecte benefice asupra sistemului locomotor și nervos. Datorită compoziției minerale, aceste ape sunt utilizate în tratamente pentru afecțiuni reumatologice și neurologice. Stațiunea oferă băi termale moderne, spații de relaxare și un parc natural ce completează atmosfera de liniște și refacere. Climatul blând și peisajele verzi atrag turiști atât pentru tratamente, cât și pentru recreere. Băile Călacea reprezintă o alegere ideală pentru cei care caută sănătate, odihnă și echilibru natural.','images/calacea1.jpg, images/calacea2.jpg, images/calacea3.jpg, images/calacea4.jpg'),
(11,'Călimănești-Căciulata, situată pe pitoreasca Vale a Oltului, este una dintre cele mai apreciate stațiuni balneare din România, recunoscută pentru apele sale termale cu proprietăți curative. Stațiunea oferă baze moderne de tratament, piscine cu ape minerale și un cadru natural ideal pentru relaxare și refacere. În plus, atracțiile din zonă, precum Mănăstirea Cozia și Parcul Național Cozia, completează experiența turiștilor prin oportunități de explorare culturală și drumeții. Datorită combinației dintre beneficiile terapeutice, peisajele spectaculoase și oferta diversificată de activități, Călimănești-Căciulata rămâne o destinație de top pentru sănătate și turism.','images/calimanesti1.jpg, images/calimanesti2.jpg, images/calimanesti3.jpg, images/calimanesti4.jpg'),
(12,'Lacu Roșu, aflat în inima Carpaților Orientali, este un lac de baraj natural spectaculos, format în urma unei alunecări de teren. Înconjurat de păduri de conifere și stânci impunătoare, oferă un peisaj deosebit și un refugiu perfect pentru iubitorii de natură. Zona este ideală pentru drumeții, plimbări cu barca și explorarea impresionantelor Chei ale Bicazului. Datorită atmosferei sale liniștite și frumuseții naturale, Lacu Roșu atrage turiști în căutare de aventură, relaxare și peisaje montane deosebite, fiind una dintre cele mai pitorești destinații din România.','images/rosu1.jpg, images/rosu2.jpg, images/rosu3.jpg, images/rosu4.jpg'),
(13,'Lacu Sărat, aflat în apropierea Brăilei, este o stațiune balneară cunoscută pentru apa sărată și nămolul sapropelic cu proprietăți terapeutice. Aceste resurse naturale sunt utilizate în tratamente pentru afecțiuni reumatologice, dermatologice și ale sistemului locomotor. Stațiunea dispune de baze moderne de tratament, zone de relaxare și o plajă amenajată, oferind o combinație perfectă între terapie și recreere. Datorită climatului favorabil și efectelor benefice ale apei și nămolului, Lacu Sărat atrage anual turiști în căutare de sănătate și odihnă într-un cadru natural liniștit.','images/sarat1.jpg, images/sarat2.jpg, images/sarat3.jpg, images/sarat4.jpg'),
(14,'Ocna Sibiului, situată în apropierea Sibiului, este o stațiune balneară faimoasă pentru lacurile sărate formate în foste saline prăbușite. Apele acestor lacuri au o salinitate ridicată și sunt recunoscute pentru efectele lor terapeutice asupra afecțiunilor reumatologice, dermatologice și ale sistemului locomotor. Stațiunea oferă băi naturale, peisaje pitorești și oportunități de relaxare, atrăgând turiști în căutare de tratamente naturale și recreere. Datorită proprietăților unice ale apei și nămolului, Ocna Sibiului este cunoscută și sub denumirea de „Litoralul Ardealului”, fiind o destinație ideală pentru sănătate și odihnă.','images/ocna1.jpg, images/ocna2.jpg, images/ocna3.jpg, images/ocna4.jpg'),
(15,'Ocna Șugatag, situată în inima Maramureșului, este o stațiune balneară cunoscută pentru apele sărate provenite din foste exploatări miniere. Aceste ape au efecte terapeutice remarcabile, fiind utilizate în tratarea afecțiunilor reumatologice, neurologice și ale sistemului locomotor. Stațiunea oferă piscine cu apă sărată, baze moderne de tratament și un cadru natural deosebit, ideal pentru relaxare și refacere. În plus, turiștii pot descoperi frumusețea tradițiilor maramureșene, bisericile de lemn și ospitalitatea localnicilor. Ocna Șugatag rămâne o destinație perfectă pentru cei care caută sănătate, liniște și autenticitate.','images/sugatag1.jpg, images/sugatag2.jpg, images/sugatag3.jpg, images/sugatag4.jpg'),
(16,'Praid, aflat în județul Harghita, este o destinație cunoscută pentru Salina Praid, una dintre cele mai mari saline din Europa, recunoscută pentru efectele sale benefice asupra afecțiunilor respiratorii. În subteran, salina oferă un microclimat unic, ideal pentru tratamente, dar și zone de agrement și spații de joacă. Pe lângă terapia salină, stațiunea pune la dispoziție băi sărate, trasee de drumeție prin peisajele montane și oportunități de explorare a tradițiilor secuiești. Datorită combinației dintre tratament, relaxare și natură, Praid atrage anual numeroși turiști în căutare de sănătate și odihnă.','images/praid1.jpg, images/praid2.jpg, images/praid3.jpg, images/praid4.jpg'),
(17,'Slănic Moldova, situată în pitorescul decor al Carpaților Orientali, este o stațiune balneară apreciată pentru izvoarele sale minerale cu efecte benefice asupra sănătății. Cunoscute pentru tratarea afecțiunilor digestive, renale și respiratorii, aceste ape atrag turiști în căutare de tratamente naturale. Stațiunea oferă aer curat, peisaje montane spectaculoase și multiple oportunități de recreere, inclusiv drumeții, sporturi de iarnă și plimbări relaxante prin Parcul Central. Datorită combinației dintre terapii balneare și activități în aer liber, Slănic Moldova este o destinație ideală pentru sănătate, relaxare și refacere.','images/slanic1.jpg, images/slanic2.jpg, images/slanic3.jpg, images/slanic4.jpg'),
(18,'Sovata, situată în inima Transilvaniei, este o stațiune balneară de renume, faimoasă pentru Lacul Ursu, un lac helioterm unic în Europa. Datorită combinației dintre apa sărată și stratificarea termică, lacul are efecte terapeutice remarcabile, fiind recomandat pentru tratarea afecțiunilor reumatologice, ginecologice și dermatologice. Pe lângă băile curative, stațiunea oferă trasee de drumeție prin păduri pitorești, centre de wellness și spa, precum și oportunități de relaxare pe tot parcursul anului. Atmosfera liniștită, aerul curat și frumusețea naturală transformă Sovata într-o destinație ideală pentru sănătate și recreere.','images/sovata1.jpg, images/sovata2.jpg, images/sovata3.jpg, images/sovata4.jpg');























CREATE TABLE feedback (
  id int AUTO_INCREMENT PRIMARY KEY,
  name varchar(20) NOT NULL,
  email varchar(30) NOT NULL,
  feedbk varchar(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE table auth(
  id int AUTO_INCREMENT PRIMARY KEY,
  username varchar(100) UNIQUE NOT NULL,
  parola varchar(100) NOT NULL
)

INSERT INTO auth (username, parola) 
VALUES ('admin', '$2y$10$wkpKzDjYBa5qM8SglA1D0OSrB4eQHCpyn5/D9N7A1csQexnQpiO2G');
# a se adauga mai multe exemple
