CREATE DATABASE ghid_turistic;
USE ghid_turistic;

CREATE TABLE destinatii (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    descriere TEXT,
    imagine VARCHAR(255) -- Stocăm URL-ul imaginii
);

INSERT INTO destinatii (nume,descriere,  imagine) VALUES
 ('Palatul Parlamentului','Palatul Parlamentului din București, România (cunoscut înainte de revoluția din 1989 sub numele de Casa Republicii sau Casa Poporului[2]), măsoară 270 m pe 240 m, 84 m înălțime, și 92 m sub pământ realizat în spiritul arhitecturii realist socialiste.[3] Are 9 niveluri la suprafață și alte 9 subterane. Conform World Records Academy, Palatul Parlamentului este a treia cea mai mare clădire administrativă pentru uz civil ca suprafață din lume, cea mai scumpă clădire administrativă din lume, și cea mai grea clădire din lume.[4] Clădirea Palatului Parlamentului este situată în partea centrală a Bucureștiului (sector 5), pe locul care astăzi se cheamă Dealul Arsenalului, încadrat de strada Izvor la vest și nord-vest, Bulevardul Națiunile Unite spre nord, Bulevardul Libertății la est și Calea 13 Septembrie la sud',''),
 ('Castelul Bran', 'Castelul Bran este situat în inima Transilvaniei, aproape de Brașov, este adesea asociat cu legenda lui Dracula, figura iconică a lui Vlad Țepeș, domnitorul Valahiei cunoscut pentru lupta împotriva invadatorilor otomani. Deși conexiunea dintre Vlad Țepeș și castel este mai mult o creație literară decât una istorică, aceasta nu a împiedicat mii de turiști să viziteze acest misterios castel în căutarea poveștilor de vampiri.'),
 ('Delta Dunării –Paradisul natural,Tulcea,Delta Dunării, cea mai mare și cea mai bine conservată deltă din Europa, este un ecosistem unic situat în estul României, acolo unde Dunărea se varsă în Marea Neagră. Este recunoscută ca sit UNESCO pentru biodiversitatea sa extraordinară, găzduind sute de specii de păsări, pești și alte animale sălbatice, multe dintre ele fiind rare sau amenințate cu dispariția. Printre cele mai cunoscute specii se numără pelicani, lebede, egrete și cormorani, care atrag pasionați de birdwatching din întreaga lume.'),
 ('Transfăgărășan – Drumul spre nori, Arge&Sibiu, ransfăgărășanul, oficial cunoscut ca DN7C, este un drum montan care traversează Munții Făgăraș, cei mai înalți munți din România. Construit în anii ’70 la ordinul lui Nicolae Ceaușescu, acesta a fost conceput ca o rută strategică militară și se întinde pe aproximativ 90 de kilometri, oferind unele dintre cele mai impresionante și dramatice peisaje montane din țară. Drumul este cunoscut pentru serpentinele sale înguste, tunelurile săpate în stâncă și viaductele spectaculoase, fiind deschis traficului doar în lunile de vară, din cauza condițiilor meteorologice severe din restul anului.  '),
 ('Castelul Corvinilor, Castelul Corvinilor, situat în Hunedoara, este un impresionant castel gotic din secolul XV, construit de Ioan de Hunedoara. Renumit pentru arhitectura sa spectaculoasă, include turnuri impunătoare, Sala Cavalerilor și o fântână legendară săpată de prizonieri turci.'),
 ('Salina Turda, Salina Turda datează din perioada romană, fiind exploatată pentru sare de peste 2.000 de ani.Primele atestări documentare datează din anul 1075, iar în Evul Mediu extracția sării era una dintre principalele activități economice din zonă.Începând cu secolul al XVII-lea, mina a fost extinsă, săpându-se manual galeriile care astăzi impresionează turiștii.Exploatarea sării a fost o activitate intensă până în 1932, când a fost închisă din motive economice.Timp de aproape 80 de ani, galeriile au fost folosite ocazional ca depozite sau adăposturi în perioade de război.În 2010, salina a fost restaurată și transformată într-unul dintre cele mai spectaculoase obiective turistice din România.'),
 ('Mocănița de pe Valea Vaserului, De luni până sâmbătă, din mai și până în octombrie, de 84 de ani, locomotiva Mocănița străbate aceeași 21,6 kilometri între Vișeu și Paltin pentru a transporta lemne și pentru a încânta turiști. Ultima locomotivă cu aburi din lume o ia din loc la 9 dimineața, te poartă prin plaiuri mureșene unde natura abia a fost atinsă de mâna omului și te aduce înapoi abia la la 3 după masă. Dacă vrei să te bucuri cât cuprinde de drumul asta, îți trebuie musai o companie pe măsură, fie ea și compania unei cărți de suflet'),
 ('Cazanele Dunării, Cazanele Dunării, situate lângă Dubova, județul Mehedinți, sunt una dintre cele mai spectaculoase zone naturale din România. Aici, Dunărea străbate Munții Carpați, formând un defileu impresionant cu pereți stâncoși abrupți. Atractii emblematice includ Chipul lui Decebal, Mănăstirea Mraconia și Peștera Ponicova. Loc ideal pentru croaziere și drumeții. '),
 ('Cimitirul Vesel de la Săpânța, Cimitirul Vesel din Săpânța, județul Maramureș, este celebru pentru crucile viu colorate și epitafurile satirice care descriu viața celor îngropați.A fost creat de Stan Ioan Pătraș în anii 1930, artist popular care a sculptat și pictat primele cruci.Crucile sunt decorate în stil tradițional maramureșean, predominant albastru și ilustrează, prin picturi naive, meseria sau modul în care persoana a trăit ori a murit.Pe fiecare cruce, se găsesc epitafuri amuzante sau ironice, scrise în versuri, care adesea conțin umor și înțelepciune populară.'),
 ('Cetatea Alba Carolina, Cetatea Alba Carolina, din Alba Iulia, județul Alba, este cea mai mare cetate din România, construită în stil Vauban în secolul XVIII. Are șapte bastioane, porți impunătoare și găzduiește Catedrala Reîntregirii. Simbol al Unirii din 1918, este o atracție turistică de top, plină de istorie.  ')
 

 CREATE TABLE orase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL, 
    populatie INT,
    descriere TEXT,
    imagine VARCHAR(255)
);
INSERT INTO orase(nume,populatie,descriere, imagine) VALUE
('București','București este capitala și cel mai mare oraș din România, având o istorie de peste 500 de ani. Orașul se distinge printr-o combinație interesantă de arhitectură istorică și modernă, cu clădiri de epocă, precum Palatul Parlamentului, și structuri contemporane. București este un important centru cultural, cu teatre, muzee și galerii de artă, iar viața sa urbană este animată de restaurante, cafenele și evenimente diverse. Orașul este, de asemenea, un hub economic major, găzduind multe instituții financiare și companii internaționale. Deși provocările urbane sunt prezente, Bucureștiul rămâne un loc dinamic și plin de oportunități.')
('Cluj-Napoca,  Cluj-Napoca este un oraș vibrant situat în centrul Transilvaniei, România, cunoscut pentru rolul său important în educație, cultură și tehnologie. Aflat pe malurile Someșului, Cluj-Napoca este un centru universitar major, găzduind Universitatea Babeș-Bolyai, una dintre cele mai vechi și prestigioase din țară. Orașul se remarcă printr-un amestec de arhitectură istorică, cum ar fi Biserica Sf. Mihail, și dezvoltări moderne, cu o viață culturală activă, evenimente și festivaluri internaționale. Cluj-Napoca este, de asemenea, un important centru tehnologic, fiind cunoscut ca un hub IT în creștere. Atmosfera sa cosmopolitană atrage turiști și investitori din întreaga lume. ')
('Iași, Iași este un oraș istoric situat în nord-estul României, fiind considerat capitala culturală a regiunii Moldova. Cu o istorie de peste 600 de ani, Iași a fost un important centru al educației și al religiei, găzduind cele mai vechi instituții de învățământ superior din țară, cum ar fi Universitatea „Alexandru Ioan Cuza”. Orașul este renumit pentru monumentele sale istorice, inclusiv Palatul Culturii și Biserica Trei Ierarhi, dar și pentru viața culturală activă. Iași este, de asemenea, un important centru economic, cu o dezvoltare semnificativă în domenii precum IT-ul, sănătatea și industria farmaceutică.')
('Constanța,Constanța este un oraș situat pe coasta Mării Negre, fiind cel mai important port al României și unul dintre cele mai vechi orașe din țară, cu o istorie ce datează de peste 2.500 de ani. Cunoscut pentru atracțiile sale turistice, Constanța oferă plaje extinse, un climat blând și o combinație de influențe culturale și istorice, inclusiv vestigii ale civilizațiilor grecești și romane. Printre obiectivele notabile se numără Cazinoul, Muzeul de Istorie Națională și Arheologie, dar și portul, care joacă un rol economic esențial. Orașul este, de asemenea, un important centru comercial și cultural al regiunii.')
('Timișoara, Timișoara este municipiul de reședință al județului Timiș, Banat, România. Se află în vestul României, aproape de frontierele cu Ungaria și Serbia, pe malul râului Bega.Numele localității provine de la cel al râului Timiș, combinat cu substantivul maghiar vár, „cetate”, adică Cetatea Timișului. Situat pe râul Bega, Timișoara este cel mai mare și important oraș al regiunii istorice Banat. Din 1848 și până în 1860 a fost capitala Voivodinei Sârbești și Banatului Timișan. După Primul Război Mondial Timișoara a intrat în componența României. În anul 1989, orașul a fost focarul Revoluției Române, care a îndepărtat de la guvernare regimul comunist.')
('Brașov,Brașov este un oraș situat în centrul României, înconjurat de Munții Carpați, cunoscut pentru peisajele sale montane și istoria medievală. Brașov este un important centru economic, cultural și turistic. Orașul este renumit pentru atracțiile sale, cum ar fi Castelul Bran, Biserica Neagră și Piața Sfatului, care atrag anual mii de turiști. De asemenea, este un important centru educațional și de cercetare, cu numeroase instituții de învățământ superior.  ')
('Craiova, Craiova este un oraș important situat în sud-vestul României, fiind reședința județului Dolj.Orașul se remarcă prin tradițiile sale istorice și culturale, având atracții precum Teatrul Național „Marin Sorescu”, Parcul Nicolae Romanescu și Catedrala Mitropolitană. Craiova este un important centru industrial, în special în domeniile automobilelor și energiei. De asemenea, orașul găzduiește Universitatea din Craiova și are o viață culturală activă, cu diverse evenimente și festivaluri pe parcursul anului.')
('Galați, Galați este un oraș situat în sud-estul României, pe malul stâng al Dunării, fiind un important port fluvial. Galați este un oraș situat în sud-estul României, pe malul stâng al Dunării, fiind un important port fluvial. Galați este cunoscut pentru industria siderurgică, chimică și metalurgică, având o infrastructură industrială dezvoltată. Pe lângă latura economică, Galați are o viață culturală activă, cu teatre, muzee și festivaluri, și găzduiește Universitatea „Dunărea de Jos”.   ')
('Oradea, Oradea este un oraș fascinant, cunoscut pentru arhitectura sa unică, cu influențe baroce și secessioniste. Palatul Vulturul Negru și Biserica cu Lună sunt doar câteva dintre monumentele sale remarcabile. Oradea este, de asemenea, un important centru termal, având băi termale care atrag turiști din întreaga lume. Orașul se află aproape de granița cu Ungaria, ceea ce îi conferă un caracter cosmopolit, iar apropierea de stațiunile de ski și de lacurile de agrement face din Oradea o destinație turistică versatilă. Oradea găzduiește și Universitatea din Oradea, un important centru educațional al regiunii ')
('Ploiești,Ploiești este un oraș cu o istorie industrială remarcabilă, cunoscut mai ales pentru tradiția sa în industria petrolieră. Este unul dintre primele orașe din lume unde au început activitățile de rafinare a petrolului, având o importanță deosebită în economia României. Orașul găzduiește și un muzeu dedicat istoriei industriei petroliere, Muzeul Ceasului „Nicolae Săftoiu”. Pe lângă această latură industrială, Ploiești are și o viață culturală activă, cu teatre, cinematografe și evenimente muzicale. De asemenea, orașul se mândrește cu parcuri verzi și o arhitectură diversă, care reflectă influențele istorice și moderne ale regiunii. ')
('Brăila,   Brăila este un oraș cu o istorie fascinantă, situat pe malul Dunării, având un port important pentru comerțul fluvial. De-a lungul secolelor, orașul a fost un punct de legătură între Est și Vest, iar astăzi încă păstrează influențe ale diverselor culturi. Brăila este cunoscută pentru arhitectura sa eclectică, ce îmbină stiluri tradiționale și moderne, și pentru Festivalul „Sărbătoarea Dunării”. Orașul are, de asemenea, un bogat patrimoniu cultural, cu teatre, muzee și monumente istorice, iar promenada de pe malul Dunării este un loc popular pentru relaxare. De asemenea, este un important centru agricol și industrial.')
('Arad, Aradul este situat în extremitatea vestică a României, în Câmpia înaltă a Aradului, la 30 de km de Munții Zarand, parte a Carpaților Occidentali. Traversat de la est la vest de râul Mureș, cuprinde în perimetrul său, în zona Pădurice, un lac natural. Pe parcursul secolelor XIX și XX, Aradul s-a afirmat ca unul dintre cele mai importante centre economice din regiune. În acest sens semnificativă este evaluarea făcută în anul 1937, potrivit căreia, raportat la activitatea celor 4001 societăți comerciale, orașul a fost considerat drept cel mai puternic centru economic din Transilvania și al patrulea din România. ')
