CREATE DATABASE ghid_turistic;
USE ghid_turistic;

CREATE TABLE destinatii (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL,
    descriere TEXT,
    imagine VARCHAR(255) -- Stocăm URL-ul imaginii
);

INSERT INTO destinatii (nume,descriere,  imagine) VALUES
 ('Palatul Parlamentului','Palatul Parlamentului din București, România (cunoscut înainte de revoluția din 1989 sub numele de Casa Republicii sau Casa Poporului[2]), măsoară 270 m pe 240 m, 84 m înălțime, și 92 m sub pământ realizat în spiritul arhitecturii realist socialiste.[3] Are 9 niveluri la suprafață și alte 9 subterane. Conform World Records Academy, Palatul Parlamentului este a treia cea mai mare clădire administrativă pentru uz civil ca suprafață din lume, cea mai scumpă clădire administrativă din lume, și cea mai grea clădire din lume.[4] Clădirea Palatului Parlamentului este situată în partea centrală a Bucureștiului (sector 5), pe locul care astăzi se cheamă Dealul Arsenalului, încadrat de strada Izvor la vest și nord-vest, Bulevardul Națiunile Unite spre nord, Bulevardul Libertății la est și Calea 13 Septembrie la sud',''),
 ('Castelul Bran', 'Castelul Bran este situat în inima Transilvaniei, aproape de Brașov, este adesea asociat cu legenda lui Dracula, figura iconică a lui Vlad Țepeș, domnitorul Valahiei cunoscut pentru lupta împotriva invadatorilor otomani. Deși conexiunea dintre Vlad Țepeș și castel este mai mult o creație literară decât una istorică, aceasta nu a împiedicat mii de turiști să viziteze acest misterios castel în căutarea poveștilor de vampiri.'),
 ('Delta Dunării –Paradisul natural,Tulcea,Delta Dunării, cea mai mare și cea mai bine conservată deltă din Europa, este un ecosistem unic situat în estul României, acolo unde Dunărea se varsă în Marea Neagră. Este recunoscută ca sit UNESCO pentru biodiversitatea sa extraordinară, găzduind sute de specii de păsări, pești și alte animale sălbatice, multe dintre ele fiind rare sau amenințate cu dispariția. Printre cele mai cunoscute specii se numără pelicani, lebede, egrete și cormorani, care atrag pasionați de birdwatching din întreaga lume.'),
 ('Transfăgărășan – Drumul spre nori, Arge&Sibiu, ransfăgărășanul, oficial cunoscut ca DN7C, este un drum montan care traversează Munții Făgăraș, cei mai înalți munți din România. Construit în anii ’70 la ordinul lui Nicolae Ceaușescu, acesta a fost conceput ca o rută strategică militară și se întinde pe aproximativ 90 de kilometri, oferind unele dintre cele mai impresionante și dramatice peisaje montane din țară. Drumul este cunoscut pentru serpentinele sale înguste, tunelurile săpate în stâncă și viaductele spectaculoase, fiind deschis traficului doar în lunile de vară, din cauza condițiilor meteorologice severe din restul anului.  '),
 ('Castelul Corvinilor, Castelul Corvinilor, situat în Hunedoara, este un impresionant castel gotic din secolul XV, construit de Ioan de Hunedoara. Renumit pentru arhitectura sa spectaculoasă, include turnuri impunătoare, Sala Cavalerilor și o fântână legendară săpată de prizonieri turci.'),
 ('Salina Turda, Salina Turda datează din perioada romană, fiind exploatată pentru sare de peste 2.000 de ani.Primele atestări documentare datează din anul 1075, iar în Evul Mediu extracția sării era una dintre principalele activități economice din zonă.Începând cu secolul al XVII-lea, mina a fost extinsă, săpându-se manual galeriile care astăzi impresionează turiștii.Exploatarea sării a fost o activitate intensă până în 1932, când a fost închisă din motive economice.Timp de aproape 80 de ani, galeriile au fost folosite ocazional ca depozite sau adăposturi în perioade de război.În 2010, salina a fost restaurată și transformată într-unul dintre cele mai spectaculoase obiective turistice din România.'),
 ('Mocănița de pe Valea Vaserului, De luni până sâmbătă, din mai și până în octombrie, de 84 de ani, locomotiva Mocănița străbate aceeași 21,6 kilometri între Vișeu și Paltin pentru a transporta lemne și pentru a încânta turiști. Ultima locomotivă cu aburi din lume o ia din loc la 9 dimineața, te poartă prin plaiuri mureșene unde natura abia a fost atinsă de mâna omului și te aduce înapoi abia la la 3 după masă. Dacă vrei să te bucuri cât cuprinde de drumul asta, îți trebuie musai o companie pe măsură, fie ea și compania unei cărți de suflet'),
 ('Cazanele Dunării, Cazanele Dunării, situate lângă Dubova, județul Mehedinți, sunt una dintre cele mai spectaculoase zone naturale din România. Aici, Dunărea străbate Munții Carpați, formând un defileu impresionant cu pereți stâncoși abrupți. Atractii emblematice includ Chipul lui Decebal, Mănăstirea Mraconia și Peștera Ponicova. Loc ideal pentru croaziere și drumeții. '),
 ('Cimitirul Vesel de la Săpânța, Cimitirul Vesel din Săpânța, județul Maramureș, este celebru pentru crucile viu colorate și epitafurile satirice care descriu viața celor îngropați.A fost creat de Stan Ioan Pătraș în anii 1930, artist popular care a sculptat și pictat primele cruci.Crucile sunt decorate în stil tradițional maramureșean, predominant albastru și ilustrează, prin picturi naive, meseria sau modul în care persoana a trăit ori a murit.Pe fiecare cruce, se găsesc epitafuri amuzante sau ironice, scrise în versuri, care adesea conțin umor și înțelepciune populară.'),
 ('Cetatea Alba Carolina, Cetatea Alba Carolina, din Alba Iulia, județul Alba, este cea mai mare cetate din România, construită în stil Vauban în secolul XVIII. Are șapte bastioane, porți impunătoare și găzduiește Catedrala Reîntregirii. Simbol al Unirii din 1918, este o atracție turistică de top, plină de istorie.  ')
 

 CREATE TABLE orase (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nume VARCHAR(100) NOT NULL, 
    descriere TEXT,
    imagine VARCHAR(255)
);

INSERT INTO orase (nume, descriere, imagine) VALUES
('București','București este capitala și cel mai mare oraș din România, având o istorie de peste 500 de ani. Orașul se distinge printr-o combinație interesantă de arhitectură istorică și modernă, cu clădiri de epocă, precum Palatul Parlamentului, și structuri contemporane. București este un important centru cultural, cu teatre, muzee și galerii de artă, iar viața sa urbană este animată de restaurante, cafenele și evenimente diverse. Orașul este, de asemenea, un hub economic major, găzduind multe instituții financiare și companii internaționale. Deși provocările urbane sunt prezente, Bucureștiul rămâne un loc dinamic și plin de oportunități.','bucuresti.jpg'),
('Cluj-Napoca','Cluj-Napoca este un oraș vibrant situat în centrul Transilvaniei, România, cunoscut pentru rolul său important în educație, cultură și tehnologie. Aflat pe malurile Someșului, Cluj-Napoca este un centru universitar major, găzduind Universitatea Babeș-Bolyai, una dintre cele mai vechi și prestigioase din țară. Orașul se remarcă printr-un amestec de arhitectură istorică, cum ar fi Biserica Sf. Mihail, și dezvoltări moderne, cu o viață culturală activă, evenimente și festivaluri internaționale. Cluj-Napoca este, de asemenea, un important centru tehnologic, fiind cunoscut ca un hub IT în creștere. Atmosfera sa cosmopolitană atrage turiști și investitori din întreaga lume.','cluj.jpg'),
('Iași','Iași este un oraș istoric situat în nord-estul României, fiind considerat capitala culturală a regiunii Moldova. Cu o istorie de peste 600 de ani, Iași a fost un important centru al educației și al religiei, găzduind cele mai vechi instituții de învățământ superior din țară, cum ar fi Universitatea „Alexandru Ioan Cuza”. Orașul este renumit pentru monumentele sale istorice, inclusiv Palatul Culturii și Biserica Trei Ierarhi, dar și pentru viața culturală activă. Iași este, de asemenea, un important centru economic, cu o dezvoltare semnificativă în domenii precum IT-ul, sănătatea și industria farmaceutică.','iasi.jpg'),
('Constanța','Constanța este un oraș situat pe coasta Mării Negre, fiind cel mai important port al României și unul dintre cele mai vechi orașe din țară, cu o istorie ce datează de peste 2.500 de ani. Cunoscut pentru atracțiile sale turistice, Constanța oferă plaje extinse, un climat blând și o combinație de influențe culturale și istorice, inclusiv vestigii ale civilizațiilor grecești și romane. Printre obiectivele notabile se numără Cazinoul, Muzeul de Istorie Națională și Arheologie, dar și portul, care joacă un rol economic esențial. Orașul este, de asemenea, un important centru comercial și cultural al regiunii.','constanta.jpg'),
('Timișoara','Timișoara este municipiul de reședință al județului Timiș, Banat, România. Se află în vestul României, aproape de frontierele cu Ungaria și Serbia, pe malul râului Bega.Numele localității provine de la cel al râului Timiș, combinat cu substantivul maghiar vár, „cetate”, adică Cetatea Timișului. Situat pe râul Bega, Timișoara este cel mai mare și important oraș al regiunii istorice Banat. Din 1848 și până în 1860 a fost capitala Voivodinei Sârbești și Banatului Timișan. După Primul Război Mondial Timișoara a intrat în componența României. În anul 1989, orașul a fost focarul Revoluției Române, care a îndepărtat de la guvernare regimul comunist.','timisoara.jpg'),
('Brașov','Brașov este un oraș situat în centrul României, înconjurat de Munții Carpați, cunoscut pentru peisajele sale montane și istoria medievală. Brașov este un important centru economic, cultural și turistic. Orașul este renumit pentru atracțiile sale, cum ar fi Castelul Bran, Biserica Neagră și Piața Sfatului, care atrag anual mii de turiști. De asemenea, este un important centru educațional și de cercetare, cu numeroase instituții de învățământ superior.','brasov.jpg'),
('Sibiu','Sibiu este un oraș situat în centrul României, în regiunea Transilvania, cunoscut pentru arhitectura sa medievală și atmosfera sa boemă. Orașul a fost Capitala Culturală Europeană în 2007 și este renumit pentru obiectivele sale turistice, cum ar fi Piața Mare, Turnul Sfatului și Podul Minciunilor. Sibiu este, de asemenea, un important centru economic și universitar, cu o viață culturală activă și evenimente culturale pe tot parcursul anului.','sibiu.jpg'),
('Pitești','Pitești este un oraș situat în sudul României, în regiunea Muntenia, fiind reședința județului Argeș. Orașul are o istorie îndelungată, cu rădăcini ce datează din perioada medievală, fiind atestat documentar încă din secolul al XIV-lea.','pitesti.jpg'),
('Craiova','Craiova este un oraș important situat în sud-vestul României, fiind reședința județului Dolj.Orașul se remarcă prin tradițiile sale istorice și culturale, având atracții precum Teatrul Național „Marin Sorescu”, Parcul Nicolae Romanescu și Catedrala Mitropolitană. Craiova este un important centru industrial, în special în domeniile automobilelor și energiei. De asemenea, orașul găzduiește Universitatea din Craiova și are o viață culturală activă, cu diverse evenimente și festivaluri pe parcursul anului.','craiova.jpg'),
('Galați','Galați este un oraș situat în sud-estul României, pe malul stâng al Dunării, fiind un important port fluvial. Galați este un oraș situat în sud-estul României, pe malul stâng al Dunării, fiind un important port fluvial. Galați este cunoscut pentru industria siderurgică, chimică și metalurgică, având o infrastructură industrială dezvoltată. Pe lângă latura economică, Galați are o viață culturală activă, cu teatre, muzee și festivaluri, și găzduiește Universitatea „Dunărea de Jos”.','galati.jpg'),
('Oradea','Oradea este un oraș fascinant, cunoscut pentru arhitectura sa unică, cu influențe baroce și secessioniste. Palatul Vulturul Negru și Biserica cu Lună sunt doar câteva dintre monumentele sale remarcabile. Oradea este, de asemenea, un important centru termal, având băi termale care atrag turiști din întreaga lume. Orașul se află aproape de granița cu Ungaria, ceea ce îi conferă un caracter cosmopolit, iar apropierea de stațiunile de ski și de lacurile de agrement face din Oradea o destinație turistică versatilă. Oradea găzduiește și Universitatea din Oradea, un important centru educațional al regiunii ','oradea.jpg'),
('Suceava','Suceava este un oraș situat în nordul României, în regiunea Bucovina, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Cetatea de Scaun a Sucevei, un important monument istoric, dar și pentru Mănăstirea Sfântul Ioan cel Nou, un important centru religios. Suceava este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat în apropierea Munților Carpați, oferind oportunități pentru turism montan și de agrement.','suceava.jpg'),
('Târgu Mureș','Târgu Mureș este un oraș situat în centrul României, în regiunea Transilvania, cunoscut pentru arhitectura sa eclectică și atmosfera sa cosmopolită. Orașul este renumit pentru Palatul Culturii, un important monument istoric, dar și pentru Piața Trandafirilor, un loc popular de întâlnire. Târgu Mureș este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea de Medicină și Farmacie. Orașul este situat în apropierea Munților Călimani, oferind oportunități pentru turism montan și de agrement.','targu_mures.jpg'),
('Baia Mare','Baia Mare este un oraș situat în nord-vestul României, în regiunea Maramureș, cunoscut pentru istoria sa minieră și peisajele sale montane. Orașul este renumit pentru Monumentul Minerului, un important simbol al orașului, dar și pentru Biserica Sfântul Nicolae, un important monument istoric. Baia Mare este un important centru cultural, cu teatre, muzee, galerii de artă și evenimente culturale care reflectă tradițiile și diversitatea regiunii.','baia_mare.jpg'),
('Satu Mare','Satu Mare este un oraș situat în nord-vestul României, aproape de granița cu Ungaria și Ucraina, fiind un important centru economic și cultural al regiunii. Orașul se remarcă prin arhitectura sa variată, influențată de diferite stiluri europene, dar și prin obiectivele sale turistice, precum Turnul Pompierilor, Catedrala Romano-Catolică și Grădina Romei. De asemenea, Satu Mare are o viață culturală activă, cu festivaluri, evenimente artistice și o comunitate multiculturală vibrantă.','satu_mare.jpg'),
('Râmnicu Vâlcea','Râmnicu Vâlcea este un oraș situat în sudul României, în regiunea Oltenia, cunoscut pentru frumusețea sa naturală și apele minerale. Orașul este renumit pentru Parcul Zăvoi, un important loc de agrement, dar și pentru Culele Brâncovenești, monumente istorice deosebite. Râmnicu Vâlcea este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru industrial și comercial al regiunii.','ramnicu_valcea.jpg'),
('Ploiești','Ploiești este un oraș cu o istorie industrială remarcabilă, cunoscut mai ales pentru tradiția sa în industria petrolieră. Este unul dintre primele orașe din lume unde au început activitățile de rafinare a petrolului, având o importanță deosebită în economia României. Orașul găzduiește și un muzeu dedicat istoriei industriei petroliere, Muzeul Ceasului „Nicolae Săftoiu”. Pe lângă această latură industrială, Ploiești are și o viață culturală activă, cu teatre, cinematografe și evenimente muzicale. De asemenea, orașul se mândrește cu parcuri verzi și o arhitectură diversă, care reflectă influențele istorice și moderne ale regiunii.','ploiesti.jpg'),
('Vaslui','Vaslui este un oraș situat în estul României, în regiunea Moldova, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Cetatea de Scaun a Vasluiului, un important monument istoric, dar și pentru Biserica „Sf. Ioan Botezătorul”, un important centru religios. Vaslui este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat în apropierea Munților Tutovei, oferind oportunități pentru turism montan și de agrement.','vaslui.jpg'),
('Tulcea','Tulcea este un oraș situat în estul României, în regiunea Dobrogea, cunoscut pentru Delta Dunării și peisajele sale naturale unice. Orașul este un important punct de plecare pentru excursii în Delta Dunării, o rezervație naturală protejată, cu o bogată biodiversitate. Tulcea este renumit pentru Muzeul de Istorie și Arheologie, dar și pentru Festivalul Internațional de Folclor „Delta Dunării”. Orașul este, de asemenea, un important centru cultural și universitar, găzduind Universitatea „Dunărea de Jos”.','tulcea.jpg'),
('Zalău','Zalău este un oraș situat în nord-vestul României, în regiunea Crișana, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Cetatea Zalău, un important monument istoric, dar și pentru Biserica „Sf. Nicolae”, un important centru religios. Zalău este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat la poalele Munților Meseș, oferind un peisaj natural deosebit și oportunități pentru drumeții și activități în aer liber.','zalau.jpg'),
('Slatina','Slatina este un oraș situat în sudul României, în regiunea Oltenia, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Parcul Central, un important loc de agrement, dar și pentru Biserica „Sf. Nicolae”, un important centru religios. Slatina este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat în apropierea Munților Vâlcan, oferind oportunități pentru turism montan și de agrement.','slatina.jpg'),
('Sfântu Gheorghe','Sfântu Gheorghe este un oraș situat în sud-estul României, în regiunea Muntenia, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Biserica „Sf. Gheorghe”, un important monument istoric, dar și pentru Parcul Central, un important loc de agrement. Sfântu Gheorghe este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat în apropierea Munților Buzău, oferind oportunități pentru turism montan și de agrement.','sfantu_gheorghe.jpg'),
('Slobozia','Slobozia este un oraș situat în sud-estul României, în regiunea Muntenia, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Parcul Central, un important loc de agrement, dar și pentru Biserica „Sf. Nicolae”, un important centru religios. Slobozia este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat în apropierea Munților Buzău, oferind oportunități pentru turism montan și de agrement.','slobozia.jpg'),
('Sighetu Marmației','Sighetu Marmației este un oraș situat în nord-vestul României, în regiunea Maramureș, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru Memorialul Victimelor Comunismului și al Rezistenței, un important loc de comemorare, dar și pentru Biserica „Sf. Nicolae”, un important centru religios. Sighetu Marmației este, de asemenea, un important centru cultural, cu teatre, muzee și evenimente culturale. Orașul este situat în apropierea Munților Maramureș, oferind oportunități pentru turism montan și de agrement.','sighetu_marmatiei.jpg'),
('Târgu Jiu','Târgu Jiu este un oraș situat în sud-vestul României, în regiunea Oltenia, cunoscut pentru sculpturile lui Constantin Brâncuși. Orașul este renumit pentru Ansamblul Monumental „Calea Eroilor”, care include celebrele sculpturi „Masa Tăcerii”, „Poarta Sărutului” și „Coloana Infinitului”.','tg_jiu.jpg'),
('Brăila','Brăila este un oraș cu o istorie fascinantă, situat pe malul Dunării, având un port important pentru comerțul fluvial. De-a lungul secolelor, orașul a fost un punct de legătură între Est și Vest, iar astăzi încă păstrează influențe ale diverselor culturi. Brăila este cunoscută pentru arhitectura sa eclectică, ce îmbină stiluri tradiționale și moderne, și pentru Festivalul „Sărbătoarea Dunării”. Orașul are, de asemenea, un bogat patrimoniu cultural, cu teatre, muzee și monumente istorice, iar promenada de pe malul Dunării este un loc popular pentru relaxare. De asemenea, este un important centru agricol și industrial.','braila.jpg'),
('Arad','Aradul este situat în extremitatea vestică a României, în Câmpia înaltă a Aradului, la 30 de km de Munții Zarand, parte a Carpaților Occidentali. Traversat de la est la vest de râul Mureș, cuprinde în perimetrul său, în zona Pădurice, un lac natural. Pe parcursul secolelor XIX și XX, Aradul s-a afirmat ca unul dintre cele mai importante centre economice din regiune. În acest sens semnificativă este evaluarea făcută în anul 1937, potrivit căreia, raportat la activitatea celor 4001 societăți comerciale, orașul a fost considerat drept cel mai puternic centru economic din Transilvania și al patrulea din România.','arad.jpg'),
('Bistrița','Bistrița este un oraș situat în nord-estul României, în regiunea Transilvania, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa medievală, cu clădiri istorice bine conservate, dar și pentru atmosfera sa boemă. Bistrița este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „Vasile Goldiș”. Orașul este situat în apropierea Munților Călimani, oferind oportunități pentru turism montan și de agrement.','bistrita.jpg'),
('Botoșani','Botoșani este un oraș situat în nord-estul României, în regiunea Moldova, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa eclectică, cu influențe baroce și neogotice, dar și pentru atmosfera sa boemă. Botoșani este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „Ștefan cel Mare”. Orașul este situat în apropierea Munților Mestecăniș, oferind oportunități pentru turism montan și de agrement.','botosani.jpg'),
('Buzău','Buzău este un oraș situat în sud-estul României, în regiunea Muntenia, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa eclectică, cu influențe neoclasice și moderne, dar și pentru atmosfera sa boemă. Buzău este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „George Bacovia”. Orașul este situat în apropierea Munților Buzău, oferind oportunități pentru turism montan și de agrement.','buzau.jpg'),
('Călărași','Călărași este un oraș situat în sud-estul României, în regiunea Muntenia, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa eclectică, cu influențe neoclasice și moderne, dar și pentru atmosfera sa boemă. Călărași este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „Dunărea de Jos”. Orașul este situat în apropierea Munților Călărași, oferind oportunități pentru turism montan și de agrement.','calarasi.jpg'),
('Deva','Deva este un oraș situat în vestul României, în regiunea Transilvania, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa medievală, cu clădiri istorice bine conservate, dar și pentru atmosfera sa boemă. Deva este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „1 Decembrie 1918”. Orașul este situat în apropierea Munților Zarand, oferind oportunități pentru turism montan și de agrement.','deva.jpg'),
('Drobeta-Turnu Severin','Drobeta-Turnu Severin este un oraș situat în sud-vestul României, pe malul Dunării, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa eclectică, cu influențe neoclasice și moderne, dar și pentru atmosfera sa boemă. Drobeta-Turnu Severin este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „Dunărea de Jos”. Orașul este situat în apropierea Munților Mehedinți, oferind oportunități pentru turism montan și de agrement.','drobeta.jpg'),
('Focșani','Focșani este un oraș situat în sud-estul României, în regiunea Moldova, cunoscut pentru istoria sa bogată și peisajele sale pitorești. Orașul este renumit pentru arhitectura sa eclectică, cu influențe baroce și neogotice, dar și pentru atmosfera sa boemă. Focșani este un important centru cultural, cu teatre, muzee și evenimente culturale, dar și un centru universitar, găzduind Universitatea „Ștefan cel Mare”. Orașul este situat în apropierea Munților Vrancea, oferind oportunități pentru turism montan și de agrement.','focsani.jpg');
